[package]
name = "eiviz-io-ndi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
crossbeam-channel.workspace = true
eiviz-core.workspace = true
eiviz-media.workspace = true
eiviz-time.workspace = true
grafton-ndi = { version = "=1.0.0", default-features = false, optional = true }
parking_lot.workspace = true
thiserror.workspace = true

[features]
default = []
ndi = ["dep:grafton-ndi"]
