[package]
name = "eiviz_mixer"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = { version = "1.25", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
openmediatransport = { git = "https://github.com/MikanseiLaboratory/openmediatransport-rs" }
pollster = "0.4"
raw-window-handle = "0.6"
thiserror = "2"
vmx = { git = "https://github.com/MikanseiLaboratory/vmx-rs" }
wgpu = { version = "30.0.1", features = ["dx12"] }
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Graphics_Direct3D", "Win32_Graphics_Direct3D11", "Win32_Graphics_Direct3D11on12", "Win32_Graphics_Direct3D12", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common", "Win32_Media_Audio", "Win32_Media_MediaFoundation", "Win32_Devices_FunctionDiscovery", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Registry", "Win32_System_Threading", "Win32_System_Variant"] }

[dev-dependencies]
pollster = "0.4"
