[package]
name = "eiviz-io-omt"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
eiviz-core.workspace = true
eiviz-media.workspace = true
eiviz-time.workspace = true
openmediatransport = { git = "https://github.com/MikanseiLaboratory/openmediatransport-rs", version = "0.1.0" }
parking_lot.workspace = true
thiserror.workspace = true
